const { initializeApp, cert } = require('firebase-admin/app');
const { getFirestore } = require('firebase-admin/firestore');
const serviceAccount = require('./habesha-hub-7bd1d-firebase-adminsdk-fbsvc-bccf6f981d.json');

initializeApp({ credential: cert(serviceAccount) });


const db = getFirestore();
const { FieldValue } = require('firebase-admin/firestore');
const businesses = [


  // ═══════════════════════════════════════════
  // SVERIGE - STOCKHOLM
  // ═══════════════════════════════════════════
  {
    name: 'Restaurang Jebena',
    category: 'Restaurant',
    address: 'Kungsklippan, 112 25 Stockholm',
    country: 'Sverige',
    phone: '08-650 42 50',
    description: 'Eritreansk och etiopisk restaurang vid Rådhuset i Stockholm. Känd för smakrika rätter, generösa portioner och gästvänlig atmosfär.',
    email: 'info@jebena.com',
    website: 'https://jebena.com',
    openingHours: 'Mån-Tor: 16:00-21:30, Fre: 16:00-22:30, Lör: 14:30-22:30, Sön: 11:00-21:30',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 59.3295, longitude: 18.0466, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Abyssinia Restaurang',
    category: 'Restaurant',
    address: 'Karlbergsvägen 46B, 113 37 Stockholm',
    country: 'Sverige',
    phone: '070-2959494',
    description: 'En av Stockholms äldsta etiopiska restauranger i Vasastan. Vann Gulddraken år 2003. Serverar injera med grytor av lamm, nöt och linser.',
    email: 'abyssiniastockholm@gmail.com',
    website: 'https://www.abyssinia.se',
    openingHours: 'Mån-Fre: 11:00-14:00 & 16:00-23:00',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 59.3429, longitude: 18.0365, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Gojo Restaurang',
    category: 'Restaurant',
    address: 'Ringvägen 161, 116 31 Stockholm',
    country: 'Sverige',
    phone: '+46 8 641 04 96',
    description: 'Autentisk etiopisk restaurang på Södermalm med afrikansk inredning och musik. Serverar traditionella rätter med injera.',
    email: '',
    website: 'https://www.gojorestaurang.se',
    openingHours: 'Mån-Tor: 17:00-23:00, Fre-Lör: 16:00-01:00',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 59.3097, longitude: 18.0600, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Gojo Hornstull',
    category: 'Restaurant',
    address: 'Högalidsgatan 52A, 117 30 Stockholm',
    country: 'Sverige',
    phone: '',
    description: 'Eritreansk og etiopisk restaurang på Hornstull. Kjent for deilig injera og smakrike grytor i rikelige porsjoner.',
    email: '',
    website: '',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 59.3167, longitude: 18.0298, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Ethiostar',
    category: 'Restaurant',
    address: 'Saltmätargatan 19A, 113 59 Stockholm',
    country: 'Sverige',
    phone: '08-30 50 44',
    description: 'Autentisk etiopisk och eritreansk restaurang i Stockholm med traditionella rätter i välkomnande atmosfär.',
    email: '',
    website: 'https://www.ethiostar.se',
    openingHours: 'Ons: 11:00-23:00, Tor: 16:00-23:00, Fre: 16:00-00:00',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 59.3436, longitude: 18.0419, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Betna Restaurang Habesha',
    category: 'Restaurant',
    address: 'Edvard Griegsgången, 164 32 Kista, Stockholm',
    country: 'Sverige',
    phone: '',
    description: 'Afrikansk restaurang i Kista med traditionell etiopisk och eritreansk mat. Känd för lammgryta och varm linssoppa.',
    email: '',
    website: '',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 59.4035, longitude: 17.9362, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Al Habesha Stockholm',
    category: 'Restaurant',
    address: 'Stockholm',
    country: 'Sverige',
    phone: '',
    description: 'Etiopisk restaurang med god mat i varm miljö. Känd för kaffeceremoni med Jebena på lördagar.',
    email: '',
    website: 'https://alhabesha.se',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 59.3293, longitude: 18.0686, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'AFRIKA Sthlm',
    category: 'Restaurant',
    address: 'Stockholm',
    country: 'Sverige',
    phone: '',
    description: 'Afrikansk restaurang med autentisk etiopisk och eritreansk mat, kenyansk och gambisk mat. Känd för god stämning.',
    email: '',
    website: 'https://afrikasthlm.se',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 59.3200, longitude: 18.0550, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Lomi Africa',
    category: 'Butikk',
    address: 'Stockholm',
    country: 'Sverige',
    phone: '',
    description: 'Afrikansk butikk med matvarer av høy kvalitet. Selger krydder, afrikansk honning og andre spesialvarer fra Afrika.',
    email: '',
    website: 'https://www.lomiafrica.se',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 59.3293, longitude: 18.0686, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },

  // ═══════════════════════════════════════════
  // SVERIGE - GÖTEBORG
  // ═══════════════════════════════════════════
  {
    name: 'Al Habesha Göteborg',
    category: 'Restaurant',
    address: 'Brahegatan 1, 415 01 Göteborg',
    country: 'Sverige',
    phone: '031-21 20 80',
    description: 'Populær etiopisk restaurang i Göteborg. Kjent for autentisk mat, vennlig personale og tradisjonell kaffeseremoni. Halal-sertifisert.',
    email: '',
    website: 'https://alhabesha.se',
    openingHours: '07:00-10:00, 11:00-21:00',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 57.7089, longitude: 11.9746, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Gezana Restaurang',
    category: 'Restaurant',
    address: 'Göteborg',
    country: 'Sverige',
    phone: '',
    description: 'Eritreansk restaurang i Göteborg med deilig injera og smakrike grytor. Kjent for kykklingklubba og sambosas med kjøttfyll.',
    email: '',
    website: '',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 57.7044, longitude: 11.9672, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Eri Meley Restaurang',
    category: 'Restaurant',
    address: 'Göteborg',
    country: 'Sverige',
    phone: '',
    description: 'Eritreansk og etiopisk restaurant i hjertet av Göteborg. Serverer tradisjonelle retter i en varm atmosfære.',
    email: '',
    website: '',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 57.7058, longitude: 11.9680, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Restaurang Simba Göteborg',
    category: 'Restaurant',
    address: 'Göteborg',
    country: 'Sverige',
    phone: '',
    description: 'Etiopisk restaurang i Göteborg som serverer autentiske retter. Kjent for injera-tallerken for to og honningvin.',
    email: '',
    website: '',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 57.7000, longitude: 11.9800, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },

  // ═══════════════════════════════════════════
  // SVERIGE - VÄSTERÅS
  // ═══════════════════════════════════════════
  {
    name: 'Habesha Restaurant Västerås',
    category: 'Restaurant',
    address: 'Stora Gatan, Västerås',
    country: 'Sverige',
    phone: '',
    description: 'Autentisk etiopisk og eritreansk restaurant i Västerås. Serverer injera med berbere-krydret grytor som kitfo, tibs wot og doro wot.',
    email: '',
    website: '',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 59.6099, longitude: 16.5448, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },

  // ═══════════════════════════════════════════
  // UK - LONDON
  // ═══════════════════════════════════════════
  {
    name: 'Adulis',
    category: 'Restaurant',
    address: '44-46 Brixton Road, Brixton, SW9 6BT London',
    country: 'UK',
    phone: '',
    description: 'Kjent som "Little Eritrea" i London. Serverer autentisk eritreansk mat inkludert tsebhi, timtimo og Adulis special med lammekuber i leirkrukke.',
    email: '',
    website: '',
    openingHours: 'Mån-Fre: 17:00-00:00, Lør-Søn: 12:00-00:00',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 51.4613, longitude: -0.1156, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Zeret Kitchen',
    category: 'Restaurant',
    address: '216-218 Camberwell Rd, Camberwell, SE5 0ED London',
    country: 'UK',
    phone: '',
    description: 'Autentisk etiopisk og eritreansk restaurant i Camberwell, London. Kjent for deilige injera-tallerkener med et stort utvalg av retter. Google-rating 4.9.',
    email: '',
    website: 'https://www.zeretkitchen.com',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 51.4782, longitude: -0.0927, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Habesha Restaurant & Bar',
    category: 'Restaurant',
    address: 'Camberwell, London',
    country: 'UK',
    phone: '',
    description: 'Etiopisk restaurant og bar i Camberwell, South London. Serverer autentisk etiopisk mat med fersk injera, kjøttretter og veganske alternativer. Rating 9.4.',
    email: '',
    website: 'https://habesharestaurantandbar.co.uk',
    openingHours: '12:00-23:00',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 51.4750, longitude: -0.0940, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Habesha Ethiopian & Eritrean Kitchen',
    category: 'Restaurant',
    address: 'Old Spitalfields Market, London E1 6AA',
    country: 'UK',
    phone: '+447956219816',
    description: 'Etiopisk og eritreansk kjøkken i Old Spitalfields Market, London. Serverer doro wet, sega kulwa og veganske retter. Åpent lørdag og søndag.',
    email: '',
    website: '',
    openingHours: 'Lør-Søn: 11:00-17:30',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 51.5196, longitude: -0.0754, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Delina Ethiopian Food',
    category: 'Restaurant',
    address: 'Arch 176, Shepherd\'s Bush Market, W12 8DF London',
    country: 'UK',
    phone: '',
    description: 'Etiopisk restaurant i Shepherd\'s Bush Market. Kjent for wot-retter fra £11.50, beyaynetu for to og etiopisk honningvin tej.',
    email: '',
    website: '',
    openingHours: 'Ons-Lør: 11:00-18:00',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 51.5043, longitude: -0.2262, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Paradise Bar & Restaurant',
    category: 'Restaurant',
    address: '10 Arnside Street, Walworth, SE17 2AP London',
    country: 'UK',
    phone: '',
    description: 'Familiedrevet eritreansk og etiopisk restaurant i Walworth. Serverer derho, tibsi og etiopisk kaffe med tradisjonell musikk.',
    email: '',
    website: '',
    openingHours: 'Søn-Tor: 11:00-00:00, Fre-Lør: 11:00-00:30',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 51.4878, longitude: -0.0966, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Habesha Village',
    category: 'Restaurant',
    address: 'Brixton, London',
    country: 'UK',
    phone: '',
    description: 'Koselig etiopisk restaurant i Brixton med tradisjonell dekor. Vegansk meny med rødt fløyelskake til etiopisk kaffe.',
    email: '',
    website: '',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 51.4613, longitude: -0.1148, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Mosob',
    category: 'Restaurant',
    address: 'Maida Hill, London',
    country: 'UK',
    phone: '',
    description: 'Eritreansk og etiopisk restaurant i Maida Hill. Kjent for ye\'doro wot og smakfulle samosas med lammekjøtt.',
    email: '',
    website: '',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 51.5221, longitude: -0.1953, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Beza Restaurant',
    category: 'Restaurant',
    address: '8A Sayer Street, Elephant & Castle, SE17 1FH London',
    country: 'UK',
    phone: '',
    description: 'Etiopisk og eritreansk restaurant ved Elephant & Castle. Serverer autentiske retter med Habesha Beer. Preset menu fra £19.',
    email: '',
    website: '',
    openingHours: 'Tir-Lør: 12:00-22:00',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 51.4940, longitude: -0.1010, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Abugida Ethiopian',
    category: 'Restaurant',
    address: '457 North End Road, SW6 1NZ, Fulham London',
    country: 'UK',
    phone: '',
    description: 'Autentisk etiopisk restaurant i Fulham, London. Serverer tradisjonelle etiopiske retter i en innbydende atmosfære.',
    email: '',
    website: 'https://abugida.co.uk',
    openingHours: '12:00-23:00',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 51.4721, longitude: -0.2019, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },

  // ═══════════════════════════════════════════
  // TYSKLAND - BERLIN
  // ═══════════════════════════════════════════
  {
    name: 'Bejte Ethiopia Restaurant',
    category: 'Restaurant',
    address: 'Nollendorfplatz, Berlin',
    country: 'Tyskland',
    phone: '',
    description: 'Autentisk etiopisk restaurant nær Nollendorfplatz i Berlin. Kjent for rikelige porsjoner, kaffeseremoni og gratis popcorn. Rating 4.4 på Tripadvisor.',
    email: '',
    website: '',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 52.4994, longitude: 13.3534, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Langano Restaurant Berlin',
    category: 'Restaurant',
    address: 'Kohlfurter Str. 44, 10999 Berlin-Kreuzberg',
    country: 'Tyskland',
    phone: '030/61507103',
    description: 'Etiopisk restaurant i hjertet av Kreuzberg, Berlin. Serverer autentiske etiopiske retter med injera i en koselig atmosfære.',
    email: '',
    website: '',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 52.4990, longitude: 13.4230, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Lalibela Restaurant Berlin',
    category: 'Restaurant',
    address: 'Herrfurthstr. 32, 12049 Berlin',
    country: 'Tyskland',
    phone: '0163-6444968',
    description: 'Etiopisk restaurant i Berlin nær Boddinstraße. Serverer tradisjonelle etiopiske retter i en varm og innbydende atmosfære.',
    email: '',
    website: '',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 52.4760, longitude: 13.4310, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'TZOM Eritrean Restaurant',
    category: 'Restaurant',
    address: 'Kaiserin-Augusta-Allee 46, 10589 Berlin',
    country: 'Tyskland',
    phone: '',
    description: 'Koselig eritreansk restaurant i Berlin med autentisk hjemmelaget mat. Serverer meaddi mix for to med shiro, zigni og ztni dorho.',
    email: '',
    website: '',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 52.5200, longitude: 13.3100, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },

  // ═══════════════════════════════════════════
  // TYSKLAND - HAMBURG
  // ═══════════════════════════════════════════
  {
    name: 'Ade Habesha Restaurant',
    category: 'Restaurant',
    address: 'Ferdinandstraße 36, 20095 Hamburg',
    country: 'Tyskland',
    phone: '',
    description: 'Eritreansk og etiopisk restaurant i Hamburg. Serverer autentiske retter fra Eritrea og Etiopia med ferske ingredienser i familiær atmosfære.',
    email: '',
    website: 'https://www.adehabesha.de',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 53.5511, longitude: 10.0147, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'ETHIO Restaurant Hamburg',
    category: 'Restaurant',
    address: 'Rothestraße 38, 22765 Hamburg',
    country: 'Tyskland',
    phone: '0151/17600647',
    description: 'Etiopisk restaurant i Hamburg med spesialiteter fra Etiopia. Serverer tradisjonelle retter i en varm og innbydende atmosfære.',
    email: '',
    website: 'https://www.ethiorestaurant.de',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 53.5580, longitude: 9.9430, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },

  // ═══════════════════════════════════════════
  // DANMARK - KØBENHAVN
  // ═══════════════════════════════════════════
  {
    name: 'Ma\'ed Ethiopian Restaurant',
    category: 'Restaurant',
    address: 'Griffenfeldsgade 7, 2200 København',
    country: 'Danmark',
    phone: '+4531842453',
    description: 'Etiopisk restaurant i København. Kjent for autentisk mat til rimelige priser. Serverer injera med ulike gryter.',
    email: '',
    website: '',
    openingHours: 'Man-Søn: 12:00-23:00',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 55.6889, longitude: 12.5419, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Hidmona Restaurant',
    category: 'Restaurant',
    address: 'København',
    country: 'Danmark',
    phone: '+4529353530',
    description: 'Eldste etiopiske restaurant i København. Serverer eritreansk og etiopisk mat med lang tradisjon.',
    email: '',
    website: '',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 55.6761, longitude: 12.5683, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },

  // ═══════════════════════════════════════════
  // NEDERLAND - AMSTERDAM
  // ═══════════════════════════════════════════
  {
    name: 'Restaurant Semhar',
    category: 'Restaurant',
    address: 'Amsterdam',
    country: 'Nederland',
    phone: '',
    description: 'Populær etiopisk og eritreansk restaurant i Amsterdam. Kjent for fargerike retter, krydrede sauser og koselig atmosfære med terrasse.',
    email: '',
    website: '',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 52.3676, longitude: 4.9041, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Fenan Klein Afrika',
    category: 'Restaurant',
    address: 'Amsterdam',
    country: 'Nederland',
    phone: '',
    description: 'Eritreansk restaurant i hjertet av Amsterdam. Serverer tradisjonelle retter fra Eritrea inkludert injera og kifto.',
    email: '',
    website: '',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 52.3600, longitude: 4.8900, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Eetcafé Ibis Amsterdam',
    category: 'Kafé',
    address: 'Amsterdam',
    country: 'Nederland',
    phone: '',
    description: 'Etiopisk kafé og restaurant i Amsterdam. Kjent for Ibis special-menyen med et stort fat med ulike retter og etiopisk øl Habesha.',
    email: '',
    website: '',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 52.3650, longitude: 4.9100, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },

  // ═══════════════════════════════════════════
  // NEDERLAND - DEN HAAG
  // ═══════════════════════════════════════════
  {
    name: 'Habesha Savanna Eetcafé',
    category: 'Kafé',
    address: 'Noordeinde 166, 2514 GR Den Haag',
    country: 'Nederland',
    phone: '',
    description: 'Etiopisk og eritreansk kafé i Den Haag. Kjent for eier Sophia og vennlig personale. Serverer delte retter til rimelige priser.',
    email: '',
    website: 'https://www.savannaeetcafe.nl',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 52.0799, longitude: 4.3113, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Habesha Bar Restaurant & Lounge Den Haag',
    category: 'Restaurant',
    address: 'Gedempte Burgwal 33, 2512 BS Den Haag',
    country: 'Nederland',
    phone: '',
    description: 'Eritreansk restaurant og lounge i Den Haag. Kjent for vennlig og høflig personale og autentiske etiopiske retter.',
    email: '',
    website: '',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 52.0780, longitude: 4.3140, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },

  // ═══════════════════════════════════════════
  // FRANKRIKE - PARIS
  // ═══════════════════════════════════════════
  {
    name: 'Restaurant Habesha Paris',
    category: 'Restaurant',
    address: '19 Rue Copreaux, 75015 Paris',
    country: 'Frankrike',
    phone: '01 43 06 09 42',
    description: 'Populær etiopisk restaurant i Paris med rating 4.8 og 629 anmeldelser. Kjent for autentisk mat, veggieplass og glutenfri injera. Åpent daglig fra 12:30.',
    email: '',
    website: '',
    openingHours: 'Daglig: 12:30-22:00',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 48.8456, longitude: 2.3072, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Menelik Restaurant Paris',
    category: 'Restaurant',
    address: '4 rue Sauffroy, 75017 Paris',
    country: 'Frankrike',
    phone: '01-46270082',
    description: 'Etiopisk restaurant i Paris 17. arrondissement. Serverer tradisjonelle etiopiske retter i en varm atmosfære.',
    email: '',
    website: '',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 48.8875, longitude: 2.3189, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  // ═══════════════════════════════════════════
  // BELGIA - BRUSSEL (størst by)
  // ═══════════════════════════════════════════



  {
    name: 'Habesha Village Brussels',
    category: 'Restaurant',
    address: 'Brussel, 1000 Brussels',
    country: 'Belgia',
    phone: '',
    description: 'Koselig etiopisk restaurant i hjertet av Brussel. Kjent for hjemmelaget mat, honningvin og varm atmosfære. Populær blant både turister og lokale.',
    email: '',
    website: '',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 50.8503, longitude: 4.3517, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Habesha Restaurant Brussels',
    category: 'Restaurant',
    address: 'Brussel',
    country: 'Belgia',
    phone: '',
    description: 'Autentisk etiopisk restaurant i Brussel. Serverer tradisjonelle retter med injera og etiopisk musikk. Eid og drevet av etiopere.',
    email: '',
    website: 'https://habesha-restaurant.be',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 50.8465, longitude: 4.3520, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },

  // ═══════════════════════════════════════════
  // BELGIA - ANTWERPEN (nest størst)
  // ═══════════════════════════════════════════
  {
    name: 'Little Ethiopia Antwerp',
    category: 'Restaurant',
    address: 'Antwerpen',
    country: 'Belgia',
    phone: '',
    description: 'Etiopisk restaurant i Antwerpen med fantastisk utsikt og varm atmosfære. Serverer tradisjonell injera og etiopiske retter.',
    email: '',
    website: '',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 51.2194, longitude: 4.4025, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Zula Habesha',
    category: 'Butikk',
    address: 'Antwerpen',
    country: 'Belgia',
    phone: '',
    description: 'Eritreansk og etiopisk spesialbutikk i Antwerpen. Selger tradisjonell mat, krydder, klær, hjemmedekor, skjønnhetsprodukter og hårstell. One-stop-shop for Habesha-kulturen.',
    email: '',
    website: 'https://zulahabesha.com',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 51.2200, longitude: 4.4010, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Mosob Eet-Cafe Antwerpen',
    category: 'Kafé',
    address: 'Antwerpen',
    country: 'Belgia',
    phone: '',
    description: 'Eritreansk kafé i Antwerpen. Kjent for varm gjestfrihet og autentiske eritreanske retter. Enkel atmosfære med fokus på matkvalitet.',
    email: '',
    website: '',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 51.2180, longitude: 4.4030, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },

  // ═══════════════════════════════════════════
  // CANADA - TORONTO (størst by)
  // ═══════════════════════════════════════════
  {
    name: 'Ethiopian House Restaurant',
    category: 'Restaurant',
    address: '4 Irwin Avenue, Toronto, ON M4Y 1K9',
    country: 'Canada',
    phone: '(416) 923-5438',
    description: 'En av Torontos beste etiopiske restauranter i sentrum. Serverer tradisjonell etiopisk mat med vegetariske og kjøttbaserte alternativer. Eid av familien.',
    email: '',
    website: '',
    openingHours: 'Man-Søn: 12:00-00:00',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 43.6658, longitude: -79.3831, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'African Palace Toronto',
    category: 'Restaurant',
    address: '977 Bloor Street West, Toronto',
    country: 'Canada',
    phone: '(416) 539-0259',
    description: 'Eritreansk og etiopisk restaurant ved Dovercourt og Bloor i Toronto. Serverer kveldsmat 7 kvelder i uken med tradisjonell kaffeseremoni og 100% teff injera.',
    email: '',
    website: '',
    openingHours: 'Man-Søn: 16:00-23:00',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 43.6615, longitude: -79.4285, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Lucy Ethiopian & Eritrean Restaurant',
    category: 'Restaurant',
    address: 'Toronto, ON',
    country: 'Canada',
    phone: '',
    description: 'Familiedrevet etiopisk og eritreansk restaurant i Toronto. Kjent for spicy lam tibs i sizzling jerngryte, generøse porsjoner og utmerket kaffeseremoni.',
    email: '',
    website: '',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 43.6550, longitude: -79.3900, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Rendez-Vous Ethiopian and Eritrean',
    category: 'Restaurant',
    address: 'Toronto, ON',
    country: 'Canada',
    phone: '',
    description: 'Tradisjonell Habesha-matlaging i Toronto med krydrede grytor, tibs og injera. Deler-tallerken for veganere og kjøttetere. Koselig nabolagsrestaurant med uteplass.',
    email: '',
    website: '',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 43.6600, longitude: -79.4100, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Maida Restaurant & Lounge Toronto',
    category: 'Restaurant',
    address: 'Toronto, ON',
    country: 'Canada',
    phone: '',
    description: 'Eritreansk og etiopisk restaurant og lounge i Toronto. Spesialiserer seg på autentiske retter fra Eritrea og Etiopia i en moderne setting.',
    email: '',
    website: '',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 43.6620, longitude: -79.3850, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },

  // ═══════════════════════════════════════════
  // CANADA - VANCOUVER (nest størst)
  // ═══════════════════════════════════════════
  {
    name: 'Harambe Ethiopian Restaurant',
    category: 'Restaurant',
    address: '2149 Commercial Drive, Vancouver, BC V5N 4B3',
    country: 'Canada',
    phone: '(604) 216-1060',
    description: 'En av Vancouvers mest populære etiopiske restauranter på Commercial Drive. Kjent for autentisk mat, levende afrikansk kunst og musikk. Over 20 år i drift.',
    email: '',
    website: 'https://harambeethiopianrestaurant.com',
    openingHours: 'Man-Søn: 12:00-23:00',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 49.2581, longitude: -123.0693, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Fassil Ethiopian Restaurant',
    category: 'Restaurant',
    address: '736 East Broadway, Vancouver, BC V5T 1X9',
    country: 'Canada',
    phone: '(604) 879-2001',
    description: 'Familieskjørt etiopisk restaurant nær Fraser og East Broadway i Vancouver. En av de eldste etiopiske restaurantene i byen. Rating 4.5 på Tripadvisor.',
    email: '',
    website: 'https://www.fassil.ca',
    openingHours: 'Man-Søn: 12:00-23:00',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 49.2637, longitude: -123.0857, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Axum Ethiopian Restaurant Vancouver',
    category: 'Restaurant',
    address: '1279 E Hastings St, Vancouver, BC V6A 0G8',
    country: 'Canada',
    phone: '(604) 253-2986',
    description: 'Moderne etiopisk restaurant i Vancouver med tradisjonelle oppskrifter. Kjent for kjøtt- og grønnsaksplatter, etiopisk kaffeseremoni og godt utvalg av viner.',
    email: '',
    website: 'https://axumrestaurant.ca',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 49.2820, longitude: -123.0620, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Red Sea Café Vancouver',
    category: 'Restaurant',
    address: '670 East Broadway, Vancouver, BC',
    country: 'Canada',
    phone: '604-873-3332',
    description: 'Autentisk eritreansk og etiopisk restaurant på East Broadway i Vancouver. Kjent for tradisjonelle retter med injera.',
    email: '',
    website: '',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 49.2637, longitude: -123.0900, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },

  // ═══════════════════════════════════════════
  // USA - WASHINGTON DC (størst Habesha-befolkning)
  // ═══════════════════════════════════════════
  {
    name: 'Habesha Market & Carry-Out DC',
    category: 'Restaurant',
    address: '1919 9th St NW, Washington, DC 20001',
    country: 'USA',
    phone: '(202) 232-1919',
    description: 'Mest populære etiopiske restaurant i Washington DC. Drevet av tre etiopiske brødre i over 20 år. Kjent som oppfinnerne av KINTOT. Åpent 8:30-23:00.',
    email: '',
    website: 'https://habeshamarket.com',
    openingHours: 'Man-Søn: 08:30-23:00',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 38.9127, longitude: -77.0229, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Dukem Ethiopian Restaurant DC',
    category: 'Restaurant',
    address: '1114-1118 U St NW, Washington, DC 20009',
    country: 'USA',
    phone: '(202) 667-8735',
    description: 'Ikonisk etiopisk restaurant på U Street i DC. Kåret til beste etiopiske restaurant av Washington City Paper 2008-2012. 150 seter med live underholdning.',
    email: '',
    website: '',
    openingHours: 'Man-Tor: 17:00-22:00, Fre: 17:00-23:00, Lør-Søn: 12:00-23:00',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 38.9172, longitude: -77.0310, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Ethiopic Restaurant DC',
    category: 'Restaurant',
    address: '401 H St NE, Washington, DC 20002',
    country: 'USA',
    phone: '(202) 675-2066',
    description: 'Populær etiopisk restaurant på H Street i Washington DC. Serverer autentiske etiopiske retter med injera i en moderne og innbydende atmosfære.',
    email: '',
    website: '',
    openingHours: 'Tir-Tor: 17:00-22:00, Fre-Lør: 12:00-22:00, Søn: 12:00-21:00',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 38.8996, longitude: -76.9960, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Gursha Ethiopian Cuisine DC',
    category: 'Restaurant',
    address: '1195 20th St NW, Washington, DC 20036',
    country: 'USA',
    phone: '(240) 978-0219',
    description: 'Etiopisk restaurant i hjertet av Washington DC. Serverer lunsjretter fra 11:00 og middag til 21:00-22:00. Kjent for gursha-tradisjonen med håndmating.',
    email: '',
    website: '',
    openingHours: 'Man-Tor: 11:00-21:00, Fre: 11:00-22:00, Lør-Søn: 12:00-21:00',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 38.9066, longitude: -77.0436, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },

  // ═══════════════════════════════════════════
  // USA - MINNEAPOLIS (stor etiopisk befolkning)
  // ═══════════════════════════════════════════
  {
    name: 'The Red Sea Ethiopian Restaurant',
    category: 'Restaurant',
    address: '320 Cedar Ave South, Minneapolis, MN 55454',
    country: 'USA',
    phone: '',
    description: 'Minneapolis første etiopiske restaurant, åpnet i 1990. Ligger på West Bank/Cedar-Riverside. Serverer autentiske etiopiske og eritreanske retter med øl, vin og cocktails.',
    email: '',
    website: 'https://theredseampls.com',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 44.9715, longitude: -93.2460, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Mesob Ethiopian Restaurant Minneapolis',
    category: 'Restaurant',
    address: '3915 Hiawatha Ave, Minneapolis, MN 55406',
    country: 'USA',
    phone: '(612) 839-5868',
    description: 'Autentisk etiopisk restaurant i Minneapolis. Kjent for perfekt injera og doro wot. Tilbyr tradisjonell kaffeseremoni og catering for bryllup og arrangementer.',
    email: '',
    website: 'https://mesobmn.com',
    openingHours: 'Man-Søn: 11:00-22:00',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 44.9380, longitude: -93.2220, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Meseret Ethiopian Restaurant',
    category: 'Restaurant',
    address: '3867 Minnehaha Ave, Minneapolis, MN 55406',
    country: 'USA',
    phone: '(612) 354-4419',
    description: 'Autentisk etiopisk restaurant på Minnehaha Ave i Minneapolis. Kjent for vegansk og vegetarisk søndagsbuffet og kaffeseremoni med tradisjonell røkelse.',
    email: '',
    website: 'https://www.meseretethiopianrestaurant.com',
    openingHours: 'Man-Søn: 11:00-22:00',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 44.9376, longitude: -93.2235, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },
  {
    name: 'Selam Restaurant Minneapolis',
    category: 'Restaurant',
    address: '3860 Minnehaha Avenue, Minneapolis, MN',
    country: 'USA',
    phone: '',
    description: 'Etiopisk og eritreansk restaurant i Minneapolis. Inviterer til en kulinarisk reise gjennom Øst-Afrikas smaker med injera og krydrede grytor.',
    email: '',
    website: 'https://selamrestaurantmn.com',
    openingHours: '',
    status: 'approved', isPremium: false, imageUrl: '', galleryImages: [],
    latitude: 44.9378, longitude: -93.2230, ownerId: '',
    createdAt: getFirestore().FieldValue ? getFirestore().FieldValue.serverTimestamp() : null,
  },

];
async function addBusinesses() {
  console.log(`\n🌍 Adding ${businesses.length} Habesha businesses across Europe...\n`);

  const byCountry = {};
  businesses.forEach(b => {
    byCountry[b.country] = (byCountry[b.country] || 0) + 1;
  });

  console.log('Distribution:');
  Object.entries(byCountry).forEach(([country, count]) => {
    console.log(`  ${country}: ${count} businesses`);
  });
  console.log('');

  let success = 0;
  let failed = 0;

  for (const business of businesses) {
    try {
      const ref = await db.collection('businesses').add(business);
      console.log(`✅ ${business.country} | ${business.name}`);
      success++;
    } catch (error) {
      console.error(`❌ ${business.name}: ${error.message}`);
      failed++;
    }
  }

  console.log(`\n✅ Success: ${success} | ❌ Failed: ${failed}`);
  console.log('Done! 🎉');
  process.exit(0);
}

addBusinesses();
