// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_YioC4U8gGYv4fPVG5_FHCEdRXgJ7SnI',
    appId: '1:308436707340:web:757a5a02ec6f1ea09ae629',
    messagingSenderId: '308436707340',
    projectId: 'habesha-hub-7bd1d',
    authDomain: 'habesha-hub-7bd1d.firebaseapp.com',
    storageBucket: 'habesha-hub-7bd1d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApxpljv-UxJox94_eWDzB2pVHDRs1w-w4',
    appId: '1:308436707340:android:e6c29336bde4c1239ae629',
    messagingSenderId: '308436707340',
    projectId: 'habesha-hub-7bd1d',
    storageBucket: 'habesha-hub-7bd1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACEWzlI3wG1cSjfSlIS0vy-r4vdj6rQhc',
    appId: '1:308436707340:ios:015ff7e8e5d97aef9ae629',
    messagingSenderId: '308436707340',
    projectId: 'habesha-hub-7bd1d',
    storageBucket: 'habesha-hub-7bd1d.firebasestorage.app',
    iosBundleId: 'com.example.habeshaHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACEWzlI3wG1cSjfSlIS0vy-r4vdj6rQhc',
    appId: '1:308436707340:ios:015ff7e8e5d97aef9ae629',
    messagingSenderId: '308436707340',
    projectId: 'habesha-hub-7bd1d',
    storageBucket: 'habesha-hub-7bd1d.firebasestorage.app',
    iosBundleId: 'com.example.habeshaHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_YioC4U8gGYv4fPVG5_FHCEdRXgJ7SnI',
    appId: '1:308436707340:web:0e66ab28bf24a9f59ae629',
    messagingSenderId: '308436707340',
    projectId: 'habesha-hub-7bd1d',
    authDomain: 'habesha-hub-7bd1d.firebaseapp.com',
    storageBucket: 'habesha-hub-7bd1d.firebasestorage.app',
  );
}
